### ISSUE TITLE
__ASM volatile assembly problem

### ISSUE THREAD

**Issue by MaxOvervoordee** [nxp-mcuxpresso/vscode-for-mcux#16]
Hi,

I'm having difficulty finding a solution for the next problem:
When i'm building my code, i get an "inconsistent operand contraints in an 'asm'" error.
In MCUXpresso thecode builds without a problem, but in zephyr i get 8 of these errors.
The code that got the error is the following:

    #else
        __asm volatile( 
                        #if defined(__GNUC__) && !defined(__ARMCC_VERSION)  /* For GCC compiler */
                            ".syntax unified \n"           /* Using unified asm syntax */
                        #endif
                        "vcvt.s16.f32 %1, %1, #15 \n"       /* Converts between floating point and fixed point */
                        "vmov %0, %1 \n"                    /* f16Out = fltVal */
                        : "=l"(f16Out): "t"(fltVal));
    #endif

Maybe im missing something regarding cmake settings with the compiler, that's what i'm guesssing but i can't find a fix for it

**Comment by DragosMiloiuNXP** [comment]
Hi @MaxOvervoordee,

 The error is caused by differences in FPU configuration between MCUXpresso SDK and Zephyr.

 In order to change the Zephyr configuration for the project please follow these steps:
-  right click on the project and select Configure->Open Zephyr Kernel Configuration 
![image](https://github.com/nxp-mcuxpresso/vscode-for-mcux/assets/80047870/0fe84509-d626-47e9-933f-612cb378f0df)

- from the Zephyr Kernel Configuration and check the Floating Point Unti (FPU)
![image](https://github.com/nxp-mcuxpresso/vscode-for-mcux/assets/80047870/bf69aa05-a83d-4706-b4ba-dc5413789bed)

With this change the application (with the snippet above) built successfully on LPCXpresso55s69.

**Comment by MaxOvervoordee** [comment]
Yes thank you this helped me intensely!
